### ISSUE TITLE
Feature Request: Add support to specify type of install & optionally version

### ISSUE THREAD

**Issue by Marcus-James-Adams** [ocha/ansible-role-dotnet-core#6]
eg 
```
  roles:
     - ocha.dotnet-core
         - package: SDK
         - version: latest
```
Installs SDK, ASP hosting & core of the latest version of each.
```
  roles:
     - ocha.dotnet-core
         - package: hosting
         - version: 2.0.5
```
Installs verson 2.0.5 of ASP hosting & core.
and 
```
roles:
     - ocha.dotnet-core
         - package: core
```
Installs the latest version of core only.
Leaving package blank defaults to core only and version blank defaults to the latest version
[Example of differences between packages at](https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/runtime-current)
